- name: this playbook will setup ez singularity locally
  hosts: localhost
  connection: local

  tasks:
  - name: pull in any Ansible Galaxy roles from the requirements.yml
    shell: ansible-galaxy install -r requirements.yml

  - name: GET_URL; get the playbook
    get_url:
      url: "{{ ANSIBLE_PLAYBOOK_URL }}"
      dest: /opt/cacao/playbook.yml

