- name: setup and downloading play
  hosts: localhost
  connection: local

  tasks:
  - name: pull in any Ansible Galaxy roles from the requirements.yml
    shell: ansible-galaxy role install -r requirements.yml

  - name: pull in any Ansible Galaxy collections from the requirements.yml
    shell: ansible-galaxy collections install -r requirements.yml

  - name: GET_URL; get the playbook
    get_url:
      url: "{{ ANSIBLE_PLAYBOOK_URL }}"
      dest: /opt/cacao/playbook.yml

- name: executing the play
  import_playbook: /opt/cacao/playbook.yml